# Generated by Django 5.1.3 on 2025-01-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kamar', models.CharField(max_length=10)),
                ('tipe_kamar', models.CharField(max_length=50)),
                ('harga_per_malam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_ketersediaan', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kontak', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_check_in', models.DateField()),
                ('tanggal_check_out', models.DateField()),
                ('total_biaya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.kamar')),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.tamu')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField()),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Selesai', 'Selesai')], max_length=20)),
                ('pemesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.pemesanan')),
            ],
        ),
    ]
